version: 2.1
executors:
    default:
      working_directory: /go/src/github.com/yukagil/sample-go-app
      docker:
        - image: circleci/golang:1.11
          environment:
            GO111MODULE: "on"
jobs:
  test:
    executor:
      name: default
    working_directory: /go/src/github.com/yukagil/sample-go-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Vendoring
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run unit tests
          command: |
            mkdir -p /tmp/test-results
            gotestsum --junitfile /tmp/test-results/go-test-report.xml
      
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_and_upload_image:
    docker:
      - image: google/cloud-sdk
    environment:
      GCP_PROJECT_ID: packettoys-prod
      IMAGE_NANE: hello-app
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
          
      - run:
          name: gcloud auth
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud --quiet auth configure-docker
      - run:
          name: Build Image
          command: docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}:${CIRCLE_BUILD_NUM} .
      - run:
          name: Push Image
          command: docker push gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}:${CIRCLE_BUILD_NUM}


  deploy:
    parameters:
      env:
        type: enum
        enum: ["dev", "prod"]
    executor:
      name: default
    steps:
      - run:
          name: Deploy to << parameters.env >>
          command: echo "<< parameters.env >>"
      

workflows:
  build-and-deploy:
    jobs:
      - test
      - build_and_upload_image:
          requires:
            - test
      - deploy:
          name: deploy_dev
          env: dev
          requires:
            - build_and_upload_image
          filters:
            branches:
              only: develop
      - deploy:
          name: deploy_prod
          env: prod
          requires:
            - build_and_upload_image
          filters:
            branches:
              only: master