version: 2.1
executors:
    default:
      working_directory: /go/src/github.com/yukagil/sample-go-app
      docker:
        - image: circleci/golang:1.11
          environment:
            GO111MODULE: "on"
jobs:
  test:
    executor:
      name: default
    working_directory: /go/src/github.com/yukagil/sample-go-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Vendoring
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run unit tests
          command: |
            mkdir -p /tmp/test-results
            gotestsum --junitfile /tmp/test-results/go-test-report.xml
      
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_and_deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      GCP_PROJECT_ID: packettoys-prod
      GCP_COMPUTE_ZONE: us-west1-b
      IMAGE_NANE: hello-app
    parameters:
      deploy_target:
        type: enum
        enum: ["dev", "prod"]
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
          
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud --quiet auth configure-docker
            gcloud config set project ${GCP_PROJECT_ID}
            gcloud config set compute/zone ${GCP_COMPUTE_ZONE}
            gcloud container clusters get-credentials ${GCP_PROJECT_ID}
      - run:
          name: Build Image
          command: |
            docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}:${CIRCLE_BUILD_NUM} .
            docker tag gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}:${CIRCLE_BUILD_NUM} gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}:latest
      - run:
          name: Push Image
          command: docker push gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}
      - run:
          name: Deploy to << parameters.deploy_target >>
          command: |
              echo "<< parameters.deploy_target >>"
              kubectl set image deployment/hello-server hello-server=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NANE}:${CIRCLE_BUILD_NUM}
      - run: kubectl get service hello-server
      

workflows:
  build-and-deploy:
    jobs:
      - test
      - build_and_deploy:
          name: deploy_dev
          deploy_target: dev
          requires:
            - test
          filters:
            branches:
              only: develop
      - build_and_deploy:
          name: deploy_prod
          deploy_target: prod
          requires:
            - test
          filters:
            branches:
              only: master