kind: Service
apiVersion: v1
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  type: NodePort
  selector:
    app: hello-server
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080